
_gradient_huggingface: &_gradient_huggingface
  origin: https://github.com/graphcore/Gradient-HuggingFace.git
  ref: main


_common_target_repository: &_common_target_repository
    origin: notebooks/
    ref: null

gpt-j:
  source:
    paths:
    - expression: '*'
      path: stable-diffusion/
      recursive: true
    repository:
      <<: *_gradient_huggingface
      prefix: stable-diffusion/
  target:
    repository:
      <<: *_common_target_repository
      prefix: ./
