_gradient_huggingface: &_gradient_huggingface
  origin: https://github.com/graphcore/Gradient-HuggingFace.git
  ref: main


_common_target_repository: &_common_target_repository
    origin: notebooks/
    ref: null

stable-diffusion:
  source:
    paths:
      - path: stable-diffusion/image_to_image.ipynb
      - path: stable-diffusion/inpainting.ipynb
      - path: stable-diffusion/text_to_image.ipynb
      - path: stable-diffusion/text_to_image_sd2.ipynb
      - path: stable-diffusion/requirements.txt
    repository:
      <<: *_gradient_huggingface
      prefix: stable-diffusion/
  target:
    repository:
      <<: *_common_target_repository
      prefix: ./
